# Introduction

In this notebook, we will do a comprehensive analysis of the Android app market by comparing thousands of apps in the Google Play store.

# About the Dataset of Google Play Store Apps & Reviews

**Data Source:** <br>
App and review data was scraped from the Google Play Store by Lavanya Gupta in 2018. Original files listed [here](
https://www.kaggle.com/lava18/google-play-store-apps).

# Import Statements

In [2]:
import pandas as pd
import plotly.express as px

# Notebook Presentation

In [3]:
# Show numeric output in decimal format e.g., 2.15
pd.options.display.float_format = '{:,.2f}'.format

# Read the Dataset

In [4]:
df_apps = pd.read_csv('apps.csv')

# Data Cleaning

**Challenge**: How many rows and columns does `df_apps` have? What are the column names? Look at a random sample of 5 different rows with [.sample()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html).

In [34]:
df_apps.shape

(10841, 10)

In [6]:
for column in df_apps.columns:
    print(df_apps[column].name)

App
Category
Rating
Reviews
Size_MBs
Installs
Type
Price
Content_Rating
Genres
Last_Updated
Android_Ver

In [24]:
df_apps.sample(5)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
4370,We're Working Out - Al Kavadlo,HEALTH_AND_FITNESS,4.30,979,8.80,"50,000",Free,0,Everyone,Health & Fitness
9384,HTC Calendar,PRODUCTIVITY,3.90,6949,4.00,"10,000,000",Free,0,Everyone,Productivity
3468,G-Pix [Android P] Dark EMUI 8/5 THEME,PERSONALIZATION,4.10,169,24.00,"10,000",Free,0,Everyone,Personalization
452,B L Enterprises,FINANCE,NaN,2,6.90,10,Free,0,Everyone,Finance
8631,Coloring & Learn,FAMILY,4.40,12753,51.00,"5,000,000",Free,0,Everyone,Educational;Creativity

### Drop Unused Columns

**Challenge**: Remove the columns called `Last_Updated` and `Android_Version` from the DataFrame. We will not use these columns.

In [8]:
df_apps = df_apps.drop(columns=["Last_Updated", "Android_Ver"])
print(df_apps.head())

                                            App         Category  Rating  \
0                       Ak Parti Yardım Toplama           SOCIAL     NaN
1                    Ain Arabic Kids Alif Ba ta           FAMILY     NaN
2  Popsicle Launcher for Android P 9.0 launcher  PERSONALIZATION     NaN
3                     Command & Conquer: Rivals           FAMILY     NaN
4                                    CX Network         BUSINESS     NaN

   Reviews  Size_MBs Installs  Type   Price Content_Rating           Genres
0        0      8.70        0  Paid  $13.99           Teen           Social
1        0     33.00        0  Paid   $2.99       Everyone        Education
2        0      5.50        0  Paid   $1.49       Everyone  Personalization
3        0     19.00        0   NaN       0   Everyone 10+         Strategy
4        0     10.00        0  Free       0       Everyone         Business

### Find and Remove NaN values in Ratings

**Challenge**: How may rows have a NaN value (not-a-number) in the Ratings column? Create DataFrame called `df_apps_clean` that does not include these rows.

In [9]:
count_nan_ratings = df_apps['Rating'].isna().sum()
print("NaN values in Ratings column:",count_nan_ratings)

NaN values in Ratings column: 1474

In [10]:
df_apps_clean = df_apps.dropna(subset=['Rating'])
print("Shape of df_apps_clean:", df_apps_clean.shape)

Shape of df_apps_clean: (9367, 10)

### Find and Remove Duplicates

**Challenge**: Are there any duplicates in data? Check for duplicates using the [.duplicated()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.duplicated.html) function. How many entries can you find for the "Instagram" app? Use [.drop_duplicates()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html) to remove any duplicates from `df_apps_clean`.

In [11]:
print("Duplicates in df_apps_clean:", df_apps_clean.duplicated().sum())

Duplicates in df_apps_clean: 476

In [12]:
df_apps_clean = df_apps_clean.drop_duplicates()

In [13]:
print("Shape of df_apps_clean after dropping duplicates:", df_apps_clean.shape)

Shape of df_apps_clean after dropping duplicates: (8891, 10)

# Find Highest Rated Apps

**Challenge**: Identify which apps are the highest rated. What problem might you encounter if you rely exclusively on ratings alone to determine the quality of an app?

In [26]:
highest_rated_apps = df_apps_clean.sort_values(by='Rating', ascending=False)
print("Highest Rated Apps:\n", highest_rated_apps.head(5))

Highest Rated Apps:
                         App Category  Rating  Reviews  Size_MBs  Installs  \
186  Basics of Orthopaedics  MEDICAL    5.00        1      5.60        10
21      KBA-EZ Health Guide  MEDICAL    5.00        4     25.00         1
28                 Ra Ga Ba     GAME    5.00        2     20.00         1
47                  Mu.F.O.     GAME    5.00        2     16.00         1
237                EC Mover     GAME    5.00        5      4.60        10

     Type  Price Content_Rating   Genres
186  Free      0       Everyone  Medical
21   Free      0       Everyone  Medical
28   Paid  $1.49       Everyone   Arcade
47   Paid  $0.99       Everyone   Arcade
237  Free      0       Everyone   Racing

# Find 5 Largest Apps in terms of Size (MBs)

**Challenge**: What's the size in megabytes (MB) of the largest Android apps in the Google Play Store. Based on the data, do you think there could be limit in place or can developers make apps as large as they please?

In [15]:
largest_apps = df_apps_clean.nlargest(5, 'Size_MBs')
print("5 Largest Apps by Size:\n", largest_apps[['App', 'Size_MBs']])

5 Largest Apps by Size:
                                                    App  Size_MBs
1795                              Navi Radiography Pro    100.00
3144                                        Vi Trainer    100.00
4176  Car Crash III Beam DH Real Damage Simulator 2018    100.00
7926                                         Post Bank    100.00
7927                       The Walking Dead: Our World    100.00

# Find the 5 App with Most Reviews

**Challenge**: Which apps have the highest number of reviews? Are there any paid apps among the top 50?

In [16]:
most_reviewed_apps = df_apps_clean.sort_values(by='Reviews', ascending=False).head(50)
print("5 Apps with Most Reviews:\n", most_reviewed_apps.head(5))
found = False
for type in most_reviewed_apps['Type']:
    if type == 'Paid':
        print("There are paid apps in the most reviewed apps list.")
        break
if not found:
    print("There are no paid apps in the most reviewed apps list.")

5 Apps with Most Reviews:
                       App       Category  Rating   Reviews  Size_MBs  \
10805            Facebook         SOCIAL    4.10  78158306      5.30
10811            Facebook         SOCIAL    4.10  78128208      5.30
10785  WhatsApp Messenger  COMMUNICATION    4.40  69119316      3.50
10797  WhatsApp Messenger  COMMUNICATION    4.40  69109672      3.50
10808           Instagram         SOCIAL    4.50  66577446      5.30

            Installs  Type Price Content_Rating         Genres
10805  1,000,000,000  Free     0           Teen         Social
10811  1,000,000,000  Free     0           Teen         Social
10785  1,000,000,000  Free     0       Everyone  Communication
10797  1,000,000,000  Free     0       Everyone  Communication
10808  1,000,000,000  Free     0           Teen         Social
There are no paid apps in the most reviewed apps list.

# Plotly Pie and Donut Charts - Visualise Categorical Data: Content Ratings

In [27]:
ratings = df_apps_clean.Content_Rating.value_counts()
ratings

Content_Rating
Everyone           7094
Teen               1022
Mature 17+          411
Everyone 10+        360
Adults only 18+       3
Unrated               1
Name: count, dtype: int64

In [29]:
fig = px.pie(labels=ratings.index,values=ratings.values,title="Content Rating",names=ratings.index,)

In [19]:
fig.update_traces(textposition='outside', textinfo='percent+label')

In [20]:
fig.show()

# Numeric Type Conversion: Examine the Number of Installs

**Challenge**: How many apps had over 1 billion (that's right - BILLION) installations? How many apps just had a single install? 

Check the datatype of the Installs column.

Count the number of apps at each level of installations. 

Convert the number of installations (the Installs column) to a numeric data type. Hint: this is a 2-step process. You'll have make sure you remove non-numeric characters first.

In [30]:
df_apps_clean.Installs.describe()

count           8,891.00
mean       16,489,253.44
std        86,380,980.27
min                 1.00
25%            10,000.00
50%           500,000.00
75%         5,000,000.00
max     1,000,000,000.00
Name: Installs, dtype: float64

In [31]:
df_apps_clean.info()

<class 'pandas.DataFrame'>
Index: 8891 entries, 21 to 10840
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             8891 non-null   str
 1   Category        8891 non-null   str
 2   Rating          8891 non-null   float64
 3   Reviews         8891 non-null   int64
 4   Size_MBs        8891 non-null   float64
 5   Installs        8891 non-null   int64
 6   Type            8891 non-null   str
 7   Price           8891 non-null   str
 8   Content_Rating  8891 non-null   str
 9   Genres          8891 non-null   str
dtypes: float64(2), int64(2), str(6)
memory usage: 764.1 KB

In [32]:
# Installs of data type object because of the comma (,) character
df_apps_clean[['App', 'Installs']].groupby('Installs').count()

             App
Installs
1              3
5              9
10            69
50            56
100          303
500          199
1000         699
5000         426
10000        989
50000        462
100000      1110
500000       516
1000000     1486
5000000      683
10000000    1130
50000000     272
100000000    369
500000000     61
1000000000    49

In [33]:
df_apps_clean.Installs = df_apps_clean.Installs.astype(str).str.replace(',', "")

df_apps_clean.Installs = pd.to_numeric(df_apps_clean.Installs)

df_apps_clean[['App', 'Installs']].groupby('Installs').count()

             App
Installs
1              3
5              9
10            69
50            56
100          303
500          199
1000         699
5000         426
10000        989
50000        462
100000      1110
500000       516
1000000     1486
5000000      683
10000000    1130
50000000     272
100000000    369
500000000     61
1000000000    49

# Find the Most Expensive Apps, Filter out the Junk, and Calculate a (ballpark) Sales Revenue Estimate

Let's examine the Price column more closely.

**Challenge**: Convert the price column to numeric data. Then investigate the top 20 most expensive apps in the dataset.

Remove all apps that cost more than $250 from the `df_apps_clean` DataFrame.

Add a column called 'Revenue_Estimate' to the DataFrame. This column should hold the price of the app times the number of installs. What are the top 10 highest grossing paid apps according to this estimate? Out of the top 10 highest grossing paid apps, how many are games?

### The most expensive apps sub $250

### Highest Grossing Paid Apps (ballpark estimate)

# Plotly Bar Charts & Scatter Plots: Analysing App Categories

### Vertical Bar Chart - Highest Competition (Number of Apps)

### Horizontal Bar Chart - Most Popular Categories (Highest Downloads)

### Category Concentration - Downloads vs. Competition

**Challenge**: 
* First, create a DataFrame that has the number of apps in one column and the number of installs in another:

<img src=https://imgur.com/uQRSlXi.png width="350">

* Then use the [plotly express examples from the documentation](https://plotly.com/python/line-and-scatter/) alongside the [.scatter() API reference](https://plotly.com/python-api-reference/generated/plotly.express.scatter.html)to create scatter plot that looks like this. 

<img src=https://imgur.com/cHsqh6a.png>

*Hint*: Use the size, hover_name and color parameters in .scatter(). To scale the yaxis, call .update_layout() and specify that the yaxis should be on a log-scale like so: yaxis=dict(type='log')

# Extracting Nested Data from a Column

**Challenge**: How many different types of genres are there? Can an app belong to more than one genre? Check what happens when you use .value_counts() on a column with nested values? See if you can work around this problem by using the .split() function and the DataFrame's [.stack() method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.stack.html).

# Colour Scales in Plotly Charts - Competition in Genres

**Challenge**: Can you create this chart with the Series containing the genre data? 

<img src=https://imgur.com/DbcoQli.png width=400>

Try experimenting with the built in colour scales in Plotly. You can find a full list [here](https://plotly.com/python/builtin-colorscales/). 

* Find a way to set the colour scale using the color_continuous_scale parameter. 
* Find a way to make the color axis disappear by using coloraxis_showscale.

# Grouped Bar Charts: Free vs. Paid Apps per Category

**Challenge**: Use the plotly express bar [chart examples](https://plotly.com/python/bar-charts/#bar-chart-with-sorted-or-ordered-categories) and the [.bar() API reference](https://plotly.com/python-api-reference/generated/plotly.express.bar.html#plotly.express.bar) to create this bar chart: 

<img src=https://imgur.com/LE0XCxA.png>

You'll want to use the `df_free_vs_paid` DataFrame that you created above that has the total number of free and paid apps per category. 

See if you can figure out how to get the look above by changing the `categoryorder` to 'total descending' as outlined in the documentation here [here](https://plotly.com/python/categorical-axes/#automatically-sorting-categories-by-name-or-total-value).

# Plotly Box Plots: Lost Downloads for Paid Apps

**Challenge**: Create a box plot that shows the number of Installs for free versus paid apps. How does the median number of installations compare? Is the difference large or small?

Use the [Box Plots Guide](https://plotly.com/python/box-plots/) and the [.box API reference](https://plotly.com/python-api-reference/generated/plotly.express.box.html) to create the following chart. 

<img src=https://imgur.com/uVsECT3.png>

# Plotly Box Plots: Revenue by App Category

**Challenge**: See if you can generate the chart below: 

<img src=https://imgur.com/v4CiNqX.png>

Looking at the hover text, how much does the median app earn in the Tools category? If developing an Android app costs $30,000 or thereabouts, does the average photography app recoup its development costs?

Hint: I've used 'min ascending' to sort the categories.

# How Much Can You Charge? Examine Paid App Pricing Strategies by Category

**Challenge**: What is the median price price for a paid app? Then compare pricing by category by creating another box plot. But this time examine the prices (instead of the revenue estimates) of the paid apps. I recommend using `{categoryorder':'max descending'}` to sort the categories.